# Generated by Django 5.0.14 on 2025-08-18 04:39

import apps.accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0004_alter_universityimages_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.profile_images)),
                ('personal_email', models.EmailField(help_text='Use Your Personal Email Address', max_length=254, unique=True)),
                ('year', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Tell Others About Yourself', max_length=250)),
                ('current_password', models.CharField(max_length=25)),
                ('previous_password', models.CharField(blank=True, max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='university.branch')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='university.department')),
                ('university_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.university')),
            ],
            options={
                'db_table': 'userprofile',
                'ordering': ['-created_at'],
            },
        ),
    ]
