# Generated by Django 5.0.14 on 2025-08-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_password',
            field=models.CharField(max_length=128),
        ),
    ]
