# Generated by Django 5.0.14 on 2025-08-14 10:36

import apps.university.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_branch_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='image',
            field=models.ImageField(upload_to='universities_icon/'),
        ),
        migrations.CreateModel(
            name='UniversityImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.university.models.university_upload_to)),
                ('description', models.TextField(help_text='Enter Description for the image', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_id', to='university.university')),
            ],
        ),
    ]
