# Generated by Django 5.0.14 on 2025-08-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_university_image_universityimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universityimages',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'Universities_Images'},
        ),
        migrations.AlterModelTable(
            name='universityimages',
            table='university_images',
        ),
    ]
