# Generated by Django 5.0.14 on 2025-08-14 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ['category', 'name'], 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='skillscategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Skill Categories'},
        ),
    ]
