# Generated by Django 5.0.14 on 2025-08-14 10:36

import apps.category_skills.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_skills', '0002_alter_skills_options_alter_skillscategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.category_skills.models.category_skills),
        ),
        migrations.AlterField(
            model_name='skillscategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
    ]
